# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名')),
                ('describe', models.CharField(max_length=200, verbose_name='课程描述')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资源文件名')),
                ('file', models.FileField(max_length=500, upload_to='uploads/', verbose_name='课程资源文件')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程名')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '选课情况',
                'verbose_name_plural': '选课情况',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='问题标题')),
                ('content', models.CharField(max_length=200, verbose_name='问题内容')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程名')),
            ],
            options={
                'verbose_name': '课后问题',
                'verbose_name_plural': '课后问题',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('class_id', models.CharField(choices=[('dq1', '电气1班'), ('dq2', '电气2班'), ('dx1', '电信1班'), ('dx2', '电信2班')], default='dq1', max_length=3, verbose_name='班级')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号码')),
                ('school_id', models.CharField(max_length=10, verbose_name='学号')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='教师姓名')),
                ('phone_number', models.IntegerField(verbose_name='电话号码')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.AddField(
            model_name='courseselect',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Teacher', verbose_name='教师'),
        ),
    ]
