# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180917_1636'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseselect',
            unique_together=set([('student', 'course')]),
        ),
    ]
