# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180918_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=200, verbose_name='作答内容')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Question', verbose_name='问题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Student', verbose_name='作答学生')),
            ],
            options={
                'verbose_name': '学生作答情况',
                'verbose_name_plural': '学生作答情况',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'student')]),
        ),
    ]
